services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config

  server1:
    build: ./server
    container_name: server1
    ports:
      - "8081:8081"
    environment:
      - ID=001
      - PORTA=8081
    depends_on:
      - broker
    volumes:
      - ./dados/empresas.json:/app/empresas.json
      - ./dados/regiao.json:/app/regiao.json
      - ./dados/veiculos.json:/app/veiculos.json

  client:
    build: ./client
    container_name: client
    stdin_open: true
    tty: true
    depends_on:
      - broker
    volumes:
      - ./dados/regiao.json:/app/regiao.json
      - ./dados/veiculos.json:/app/veiculos.json